### ISSUE TITLE
Game asset?

### ISSUE THREAD

**Issue by null15** [nobbyfix/IllusionConnectData#1]
[deleted]

**Comment by nobbyfix** [comment]
I have them all decrypted (everything uses the same decryption algorithm except for gameconfig database), but it's not useful to upload them on github. If you want those assets you have to figure out how to decrypt them yourself.

**Comment by null15** [comment]
[deleted]

**Comment by nobbyfix** [comment]
You can PM on Discord (nobbyfix#2338) since i don't want to have this public.
