### ISSUE TITLE
Please keep updating

### ISSUE THREAD

**Issue by aaronxu106** [nobbyfix/IllusionConnectData#2]
Thank you very much for your work on datamining the game. We have an entire group of people rely on datamined data to make plans for future banners. If possible please keep updating.

Best Regards,
from IC players

**Comment by nobbyfix** [comment]
Great you're happy with this.

I don't monitor what my updating script is doing, so if there are ever missing files or if it takes longer than a day for an update, just let me know by creating a new issue here. (I wanted to move it to my server so it can update 24/7, but still have it on my PC so it will only update when I'm home and awake)
